name: WarpsPro
main: WarpsPro\WarpsPro
author: nikoskon
version: 1.0.0
api: [3.0.0, 4.0.0]
commands:
 warp:
  description: Warp Command
  usage: "/warp <warp name>"
  permission: warpspro.command.warp
 setwarp:
  description: Sets A Warp
  usage: "/setwarp <warpname>"
  permission: warpspro.command.setwarp
 delwarp:
  description: Delete A Current Warp
  usage: "/delwarp <warpname>"
  permission: warpspro.command.delwarp

permissions:
 warpspro.*:
  default: true
  description: "Access To All This Plugins Commands"
  children:
     warpspro.command.delwarp:
      description: "Allows Players To Delete Warps"
      default: true
     warpspro.command.setwarp:
      description: "Allows Player To Set Warps"
      default: true
     warpspro.command.warp:
      description: "Allows Players To Use Warps"
      default: true
